org.gradle.jvmargs=-Xmx4G
runClient.jvmArgs=-Xmx8G -Xms8G
org.gradle.daemon=false
minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
forge_version=51.0.33
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=parchment
mapping_version=2024.07.28-1.21
mod_id=spacecraftmod
mod_name=SpaceCraft mod
mod_license=MIT
mod_version=0.3.0
mod_group_id=net.foldwind.spacecraftmod
mod_authors=FoldWind, nkt
mod_description=SpaceCraft mod for «SpaceCraft» server in game «Minecraft».